/**
 * Auto-generated timeline from 逐字稿.md.
 * Maps each (chapterIndex, stepIndex) → { startMs, endMs } in milliseconds
 * from the start of the presentation.
 *
 * Generated by: node scripts/map-timeline.mjs
 */

export interface StepTime {
  startMs: number;
  endMs: number;
}

/** 2D array: TIMELINE[chapterIndex][stepIndex] = { startMs, endMs } */
export const TIMELINE: StepTime[][] = [
  [
    {
      startMs: 0,
      endMs: 6300
    },
    {
      startMs: 6300,
      endMs: 14810
    }
  ],
  [
    {
      startMs: 14810,
      endMs: 19820
    },
    {
      startMs: 19820,
      endMs: 27090
    },
    {
      startMs: 27090,
      endMs: 32622
    },
    {
      startMs: 32622,
      endMs: 36560
    },
    {
      startMs: 36560,
      endMs: 40150
    },
    {
      startMs: 40150,
      endMs: 45385
    },
    {
      startMs: 45385,
      endMs: 55542
    }
  ],
  [
    {
      startMs: 55542,
      endMs: 61430
    },
    {
      startMs: 61430,
      endMs: 69307
    },
    {
      startMs: 69307,
      endMs: 77242
    },
    {
      startMs: 77242,
      endMs: 81100
    },
    {
      startMs: 81100,
      endMs: 89220
    },
    {
      startMs: 89220,
      endMs: 93702
    },
    {
      startMs: 93702,
      endMs: 98050
    },
    {
      startMs: 98050,
      endMs: 103057
    }
  ],
  [
    {
      startMs: 103057,
      endMs: 107740
    },
    {
      startMs: 107740,
      endMs: 117310
    },
    {
      startMs: 117310,
      endMs: 121120
    },
    {
      startMs: 121120,
      endMs: 128879
    },
    {
      startMs: 128879,
      endMs: 133740
    },
    {
      startMs: 133740,
      endMs: 138450
    },
    {
      startMs: 138450,
      endMs: 145950
    },
    {
      startMs: 145950,
      endMs: 154260
    },
    {
      startMs: 154260,
      endMs: 160950
    },
    {
      startMs: 160950,
      endMs: 171410
    }
  ],
  [
    {
      startMs: 171410,
      endMs: 178450
    },
    {
      startMs: 178450,
      endMs: 183940
    },
    {
      startMs: 183940,
      endMs: 189690
    },
    {
      startMs: 189690,
      endMs: 194357
    },
    {
      startMs: 194357,
      endMs: 206957
    },
    {
      startMs: 206957,
      endMs: 213455
    },
    {
      startMs: 213455,
      endMs: 218740
    },
    {
      startMs: 218740,
      endMs: 223820
    },
    {
      startMs: 223820,
      endMs: 233445
    },
    {
      startMs: 233445,
      endMs: 237620
    }
  ],
  [
    {
      startMs: 238660,
      endMs: 242120
    },
    {
      startMs: 242120,
      endMs: 247900
    },
    {
      startMs: 247900,
      endMs: 252075
    },
    {
      startMs: 252075,
      endMs: 257670
    },
    {
      startMs: 259299,
      endMs: 264370
    },
    {
      startMs: 264370,
      endMs: 267415
    },
    {
      startMs: 267415,
      endMs: 272810
    },
    {
      startMs: 272810,
      endMs: 276862
    },
    {
      startMs: 276862,
      endMs: 281390
    },
    {
      startMs: 283035,
      endMs: 289817
    }
  ],
  [
    {
      startMs: 289817,
      endMs: 294295
    },
    {
      startMs: 294295,
      endMs: 299825
    },
    {
      startMs: 299825,
      endMs: 308060
    },
    {
      startMs: 308060,
      endMs: 313497
    },
    {
      startMs: 313497,
      endMs: 320935
    },
    {
      startMs: 320935,
      endMs: 326230
    },
    {
      startMs: 326230,
      endMs: 332490
    },
    {
      startMs: 332490,
      endMs: 339700
    },
    {
      startMs: 341740,
      endMs: 347172
    }
  ],
  [
    {
      startMs: 347172,
      endMs: 355555
    },
    {
      startMs: 355555,
      endMs: 361800
    },
    {
      startMs: 361800,
      endMs: 367000
    },
    {
      startMs: 367000,
      endMs: 369400
    }
  ]
];
